apiVersion: v1
kind: Service
metadata:
  name: servicio-servicioa
  labels:
    run: servicea-deployment
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: servicea 
